---
- name: Create Sonarr config folder
  ansible.builtin.file:
    path: "{{ config_dir }}}/sonarr"
    state: directory
    mode: "0755"

- name: Create Sonarr container
  community.docker.docker_container:
    name: sonarr
    image: ghcr.io/linuxserver/sonarr:version-3.0.9.1549
    state: started
    env:
      "PUID": 1002
      "PGID": 1002
      "TZ": "Europe/Lisbon"
    hostname: "{{ ansible_hostname }}"
    mounts:
      - source: "{{ config_dir }}}/sonarr"
        target: /config
        type: bind
        read_only: false
      - source: /media/downloads
        target: /media/downloads
        type: bind
        read_only: false
      - source: /media/tv
        target: /media/tv
        type: bind
        read_only: false
    networks:
      - name: media
      - name: proxy
    restart_policy: unless-stopped
