---
- name: Create Speedtest-exporter container
  community.docker.docker_container:
    name: sonarr
    image: ghcr.io/miguelndecarvalho/speedtest-exporter:v3.4.1
    state: started
    restart_policy: unless-stopped