---
- name: "Check if Docker is installed"
  ansible.builtin.package_facts:
    manager: "auto"

- name: "Get System Architecture"
  ansible.builtin.command:
    cmd: dpkg --print-architecture
  register: architecture
  when: "'docker' not in ansible_facts.packages"

- name: Install Docker
  ansible.builtin.include_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose: false
    docker_apt_arch: "{{ architecture.stdout }}"
